FROM node:16

ENV DEBIAN_FRONTEND=noninteractive

ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash conovatecdev
RUN usermod -aG sudo conovatecdev

RUN groupadd --gid $USER_GID conovatecdev
RUN useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash conovatecdev
RUN usermod -aG sudo conovatecdev
